title: nlamprian
header-img: site/home.jpg
email: nlamprian@gmail.com
copyright_name: Nick Lamprianidis
description: This is Nick's website. Here you can find his portfolio and blog posts on things he tackles on his daily work.
baseurl: 
url: https://nlamprian.me
google_analytics: UA-98317084-1
disqus_name: nlamprian

permalink: /:categories/:title
lsi: true
markdown: kramdown
# highlighter: rouge
kramdown:
  input: GFM 
  syntax_highlighter: rouge
permalink: pretty
paginate: 5
paginate_path: :num
exclude: [README.md]

collections:
  projects:
    output: true
    permalink: /project/:categories/:name

plugins: 
  - jekyll-paginate
  - jekyll-feed
  - jekyll-gist
  - classifier-reborn
  - rouge
  - font-awesome-sass
  - jemoji  # https://github.com/ikatyang/emoji-cheat-sheet
